apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: awscluster1
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    cloud: auto-detect
    vendor: auto-detect
    cluster.open-cluster-management.io/clusterset: clusterset
    clusterGroup: aws
spec:
  hubAcceptsClient: true

---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: azurecluster1
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    cloud: auto-detect
    vendor: auto-detect
    cluster.open-cluster-management.io/clusterset: clusterset
    clusterGroup: azure
spec:
  hubAcceptsClient: true